name: Testes de Integracao Continua

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      
jobs:
      # ==========================================
      # CONFIGURAÇÃO DO BACKEND
      # ==========================================
      
  backend:
    strategy:
      matrix:
        so: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.so }}
    defaults:
      run:
        working-directory: Desenvolvimento-de-Software
    steps:
      - name: 1. Baixar o código do repositório padrão do Github (Checkout)
        uses: actions/checkout@v4
          
      - name: 2. Configurar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 3. Instalar dependências do backend
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: 4. Rodar Backend
        run: pytest
        env:
          # Passamos uma chave fictícia aqui só por garantia para a biblioteca da Google não reclamar
          GEMINI_API_KEY: "chave_falsa_apenas_para_o_mock_passar"
        
      # ==========================================
      # CONFIGURAÇÃO DO FRONTEND
      # ==========================================
      
  frontend:
    strategy:
      matrix:
        so: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.so }}
    defaults:
      run:
        working-directory: Desenvolvimento-de-Software/frontend
    steps:
    
      - name: 1. Baixar o código do repositório padrão do Github (Checkout)
        uses: actions/checkout@v4
        
      - name: 2. Configurar Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Instalar dependências do frontend
        run: npm install
        
      - name: 4. Rodar Frontend
        run: npm run build
